### ISSUE TITLE
v 0.1.0 - help function gives internal error

### ISSUE THREAD

**Issue by toujames** [kforthman/optLog#1]
Function works but when calling the help() for documentation returns the following error.

```
> help(optLogTransform)
Error in fetch(key) : 
  lazy-load database '/media/cephfs/homefolders/librad.laureateinstitute.org/jtouthang/R/x86_64-redhat-linux-gnu-library/3.5/optLog/help/optLog.rdb' is corrupt
In addition: Warning message:
In fetch(key) : internal error -3 in R_decompress1
```

**Comment by kforthman** [comment]
I am not able to reproduce this issue on my computer. Could you try re-starting your R session and see if the issue still persists?

**Comment by toujames** [comment]
Yep that works. Restarting the R session resolved the issue.
