### ISSUE TITLE
Error in cbind(trans_opts, trans_opt) : object 'trans_opt' not found

### ISSUE THREAD

**Issue by nkirlic** [kforthman/optLog#3]
When I run the below code, this is the error message I get:
> data <- read.csv ("~/Documents/PROJECTS/PvU/analysis/PvU_pt47/PvUpt47_db_fortransformation.csv")
> data.mat <- as.matrix(data)
> colnames(data.mat) <- colnames(data)
> optLogTransform(data.mat, type = "log", skew_thresh = 1,
+                 n_trans_val = 50, scaled = T, retain_domain = F,
+                 hist_raw_folder = NA, hist_trans_folder = NA, skew_folder = NA)
Study_ID ... Skewness: 0.3
	Variable is already normal; no need for transformation.
Error in cbind(trans_opts, trans_opt) : object 'trans_opt' not found

**Comment by kforthman** [comment]
This should be fixed now. Please re-install optLog and try again. Then, please let me know if I solved the issue!

P.S. You may have already caught this, but you might want to avoid including subject id as a column in your input matrix. The function will try to normalize your ids, which I'm sure you don't want!
